POST https://online.pdp.uz/api/user_task/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYmM5NWY5OC1lZmM2LTQwYjYtYmE2Mi04YzU1MDZlNTlkODQiLCJpYXQiOjE3MTk4OTMxODksInJvbGVzIjoiUk9MRV9VU0VSLFJPTEVfTUVOVE9SIiwiZXhwIjoxNzE5OTc5NTg5fQ.tO4oS5Qh9vwfSt0D-uDGpVRgrYhlWyBgs6L4Wgx1-g-xtoAKB07PDqPKXht2bzblDNXPNQn-hEJ8_XA_ObgLKQ

{
  "rating": 5,
  "status": "COMPLETE",
  "taskId": "5f1a1214-53b4-4955-8823-81e24788fbac",
  "userId": "8a47f353-eab2-4b50-a276-ea6db428a82f"
}
###
GET https://jsonplaceholder.org/comments
###
POST http://10.10.1.187:8080/api/users
Content-Type: application/json

{
  "name": "Ali",
  "age": 15
}
###
PUT http://10.10.1.187:8080/api/users/22db4402-063b-4274-84fc-1f24da03cf6c
Content-Type: application/json

{
  "surname": "Aliyev",
  "name": "Ali",
  "age": 15

}
###
http://10.10.1.187:8080/api/users